languageCode = "en"
languageName = "English"
weight = 1
title = "zsaquarian"

[author]
name = "Sohan Talla"
headline = "Hey! I'm Sohan and I'm interested in music, STEM and CS"
links = [
  { github = "https://github.com/zsaquarian" }
]
image = "https://cdn.discordapp.com/avatars/834299848039333898/428e648654718022c7d6157ae655ed31?size=1024"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"
